### ISSUE TITLE
vscode theme?

### ISSUE THREAD

**Issue by marcos-hotmart** [mjswensen/themer#1]
The new vscode config can be a good thing as the vscode usage is growing. 
Here is the reference: https://code.visualstudio.com/docs/getstarted/theme-color-reference

**Comment by mjswensen** [comment]
Thanks, @marcos-hotmart —yes, this is definitely on the backlog. I'll keep this thread posted with progress.

**Comment by mjswensen** [comment]
@marcos-hotmart @wcastand @longsien @ShanMen Check out https://github.com/mjswensen/themer-vscode, I think I've got most of the bases covered on full VS Code support. Since I don't use VS Code full-time, if you find anything strange/broken with the theme feel free to log an issue over there.
