### ISSUE TITLE
cmd.exe theme

### ISSUE THREAD

**Issue by AmyAmy** [mjswensen/themer#11]
Would be windows only ofcource, the output would be a .reg file, like this example:

https://github.com/neilpa/cmd-colors-solarized/blob/master/solarized-light.reg

**Comment by mjswensen** [comment]
Great idea, @AmyAmy , thanks for submitting. I've got it on the backlog.

**Comment by mjswensen** [comment]
@AmyAmy , I've added basic CMD.exe support over at [themer-cmd](https://github.com/mjswensen/themer-cmd) for the CLI, as well as to [themer's GUI](https://github.com/mjswensen/themer-gui/releases/tag/v0.13.0). Thanks for the link to the example as it was very helpful.

I'm not on Windows full-time (though I did test this in a VM) so feel free to submit feedback at the [themer-cmd](https://github.com/mjswensen/themer-cmd) repository if you run into any problems.
