### ISSUE TITLE
Visual Studio template support

### ISSUE THREAD

**Issue by SamyGhannad** [mjswensen/themer#12]
Hi !
I think themer is a great idea with a great implementation, however, I really love to be able to export themes and color schemes for both Visual Studio (IDE, not VS Code) and Jetbrain's products (Intellij, Pycharm, PhpStorm, Gogland etc) .
Thanks!

**Comment by mjswensen** [comment]
Renaming this to "Visual Studio" only, as I'm currently working on the Jetbrains template. 🙂

**Comment by mjswensen** [comment]
@SamyGhannad , we now have a [JetBrains template package](https://github.com/tomselvi/themer-jetbrains), contributed by @tomselvi, FYI. 🎉
