### ISSUE TITLE
Theme Templates Suggestions

### ISSUE THREAD

**Issue by munchyfly** [mjswensen/themer#13]
WhatsApp: https://www.whatsapp.com/
Ramme: https://github.com/terkelg/ramme
Alduin: https://alduinapp.github.io/
Wox: https://github.com/Wox-launcher/Wox
Punk: https://github.com/scholtzm/punk

**Comment by mjswensen** [comment]
Official support for Wox has been added—the other tools either don't offer official support for theming or are no longer maintained.
