### ISSUE TITLE
Shade color interpolation

### ISSUE THREAD

**Issue by jathu** [mjswensen/themer#15]
I think users should only need to give the darkest color and the lightest color for the shades. Themer should automatically generate the in-between colors using this formula:

```
DARK = someRGB
LIGHT = someRGB
N = number of colors we want (8 for themer)
DELTA = (LIGHT-DARK)/(N-1)
COLORS = [DARK+(DELTA*i) for i in range(N)]
```

**Comment by mjswensen** [comment]
Fantastic idea. The [GUI version](https://github.com/mjswensen/themer-gui) actually has this feature as of [`v0.12.0`](https://github.com/mjswensen/themer-gui/releases/tag/v0.12.0), but I should add this to the CLI as well.

**Comment by mjswensen** [comment]
Thanks again, @jathu . Check out the [v3 release](https://github.com/mjswensen/themer/releases/tag/v3.0.0). 👍
