### ISSUE TITLE
5k Background Support

### ISSUE THREAD

**Issue by amcdnl** [mjswensen/themer#18]
It would be awesome if it had support for 5k backgrounds.

**Comment by mjswensen** [comment]
Hi @amcdnl , did you know that the various wallpaper packages support passing custom resolutions as arguments to `themer`? Here is an example using [themer-wallpaper-block-wave](https://github.com/mjswensen/themer-wallpaper-block-wave) to generate a 5K wallpaper:

```shell
themer \
  --colors colors.js \
  --template themer-wallpaper-block-wave \
  --themer-wallpaper-block-wave-size 5120x2880 \
  --out gen/
```

You can pass `--themer-wallpaper-block-wave-size` multiple times to get multiple resolutions (one for your 5k monitor, one for your phone or tablet, etc.). See https://github.com/mjswensen/themer-wallpaper-block-wave#custom-resolutions. All of the wallpaper packages have a similar feature.
