### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by dguo** [mjswensen/themer#2]
Hi. Before trying out themer, I checked for a license and noticed that none of the repos have a LICENSE file. I see that it's in each `package.json`'s license field, but to make it more immediately obvious, please consider adding the file. GitHub even lets you do it [from the UI](https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository).

**Comment by mjswensen** [comment]
Good call. I had thought the `package.json` field would be enough but I think you are right. I'll go ahead and add one to each repo.
