### ISSUE TITLE
Broken images in README

### ISSUE THREAD

**Issue by trevordmiller** [mjswensen/themer#21]
It seems that the README has broken images:

![image](https://user-images.githubusercontent.com/5497885/37870084-98f32aa0-2f8a-11e8-8046-43d978bf1f5c.png)

Also, thanks for adding Nova!

**Comment by mjswensen** [comment]
Thanks, @trevordmiller ! I just checked now and it appears to be all good again:

![image](https://user-images.githubusercontent.com/1591879/37917266-2b29fcc2-30db-11e8-9ae4-981f99c2e20c.png)

It's possible my hosting provider ([now.sh](https://zeit.co/now)), where these generated images are served, was experiencing an outage at the moment you saw this. 🤔 Let me know if you notice it again. 🙌

**Comment by trevordmiller** [comment]
@mjswensen Thanks for checking. I still have a bunch of 404s. Not sure if it is just me.

![image](https://user-images.githubusercontent.com/5497885/37917566-fc1c4592-30db-11e8-9c4c-879e18ec41b0.png)

**Comment by trevordmiller** [comment]
I cleared my cache as well, still same 404s

**Comment by mjswensen** [comment]
Looks like some of the images were indeed missing from my most recent deployment of [themer.mjswensen.com](https://themer.mjswensen.com)! I re-deployed them and tried some of the suggestions on [this page](https://help.github.com/articles/about-anonymized-image-urls/) for good measure; mind trying again to see if they appear for you?

**Comment by trevordmiller** [comment]
@mjswensen All fixed, no more 404s :) Thanks!

**Comment by mjswensen** [comment]
Thank YOU!  🙌
