### ISSUE TITLE
JetBrains IDE Support?

### ISSUE THREAD

**Issue by jajaperson** [mjswensen/themer#22]
This would be a very nice feature to have, seeing that JetBrains IDEs are so popular.

**Comment by mjswensen** [comment]
Hi @jajaperson , good news! Themer does actually already support the JetBrains suite of products. See [tomselvi/themer-jetbrains](https://github.com/tomselvi/themer-jetbrains).

It's also supported in the GUI as of [v0.17.0](https://github.com/mjswensen/themer-gui/releases/tag/v0.17.0).
