### ISSUE TITLE
Add Theme Template to Konsole

### ISSUE THREAD

**Issue by Dragonxero** [mjswensen/themer#27]
I have used for a while your tool for color schemes on  jetbrains, and i have to manually convert some schemes to be used on my terminal on KDE. 
Would you please consider add the template to KDE Konsole colorscheme file.
Thanks in advance

**Comment by mjswensen** [comment]
Thanks for the heads up, @Dragonxero . Do you have a link to the KDE Konsole color scheme documentation?

**Comment by Dragonxero** [comment]
I think this should be the starting point.
https://docs.kde.org/stable5/en/applications/konsole/index.html

**Comment by reinhart1010** [comment]
@mjswensen this is as easy as generating plain-text, `.colorscheme` files.

Examples:
+ https://github.com/phiggins/konsole-colors-solarized/blob/master/Solarized%20Dark.colorscheme
+ https://store.kde.org/content/show.php/Monokai+konsole+colorscheme?content=154765
+ https://github.com/nareshv/kde-konsole-colorschemes

Btw, this theme format is also compatible for KDE Plasma 4 (current version is 5.18)

**Comment by mjswensen** [comment]
Thanks for the links, @reinhart1010 ! Will get this out as quickly as I can.

**Comment by mjswensen** [comment]
@Dragonxero @TopHatCroat @layoaster @KristobalJunta @reinhart1010 this is now available for the CLI (npm package: [`@themer/konsole`](https://www.npmjs.com/package/@themer/konsole)) or in the [web UI](https://themer.dev).
