### ISSUE TITLE
Support for more than light vs. dark

### ISSUE THREAD

**Issue by alexwilson** [mjswensen/themer#28]
Hey,

Gauging interest before I have a crack at this: I'm playing with building themes dynamically from brands in https://github.com/antoligy/ft-themer and am wondering if there's appetite to support multiple "modes" (or, really, brands) instead of only Light and Dark.

It seems like a number of subcomponents, as well as all of the logic around naming/selecting colours, is based around there only light and dark themes.
What are your thoughts?

Alex

**Comment by mjswensen** [comment]
Hey Alex,

Really interesting thoughts! I think a more multi-mode approach would be really nice in a lot of cases. Though there are indeed a few challenges:

* A fair amount of light/dark assumptions made throughout the various packages, as you've pointed out
* Sometimes, this light/dark assumption is baked right into the tool (for example: vim), so a bit of thought would have to go in to breaking that 1:1 mapping
* The Web UI would need some changes as the light/dark paradigm is baked in (including backwards compatibility as light/dark appear as keys in the themes' URLs as well)

I wonder—would a library that sits on top of themer be an appropriate place to implement this multiple "brands" approach? e.g., a tool that makes multiple calls to themer and aggregates the results?
