### ISSUE TITLE
Thank you for themer

### ISSUE THREAD

**Issue by tomselvi** [mjswensen/themer#29]
Not an issue, but wanted to send some appreciation for all your great work on themer.  It has made my software development and computer usage extremely delightful.  So much so, that you inspired me to whip together https://www.github.com/tomselvi/nightenv which really wouldn't have been possible without it.

Thank you!

**Comment by mjswensen** [comment]
Thanks so much for the kind words, @tomselvi ! I'm so glad themer has been fun for you to use. Thank you so much for your contributions to themer, too. I am just checking out [nightenv](https://github.com/tomselvi/nightenv) now and it looks awesome. What a brilliant idea.
