### ISSUE TITLE
themer organization

### ISSUE THREAD

**Issue by dguo** [mjswensen/themer#3]
First of all, thanks for making themer! I have been looking for something like it for a while. I've known about [Base16](http://chriskempson.com/projects/base16/), but I stumbled upon themer today, and it looks a lot more like what I want. The gui and wallpapers are nice touches.

Since there are so many repos, I was just wondering if you have considered making a separate organization for themer. I might create a new template, but I don't know if you would prefer for that to exist under my personal account or under a hypothetical themer organization.

**Comment by mjswensen** [comment]
Hey @dguo , you're welcome! I'm glad you found it and I hope it ends up being useful to you.

That's a good thought about an organization—I think for now I'll keep the repo structure as-is, but that definitely is a good idea for the future.

Keep me in the loop as you create a new template, I'd love to see what you build. Depending on what it is we could add a link to it on the themer readme if you'd like.
