### ISSUE TITLE
Meta: Where can I find the actual Block Wave wallpaper?

### ISSUE THREAD

**Issue by drewswaycool** [mjswensen/themer#31]

**Comment by mjswensen** [comment]
Hi @drewswaycool , what do you mean by _actual_?

**Comment by drewswaycool** [comment]
I think I didn't read deep enough into what this tool is/does. It appears that you can generate a background based off of theme colors etc..?

**Comment by mjswensen** [comment]
No worries. Yes, that's correct. You give it a set of colors (or use a built-in set), and it will generate themes for your tools as well as a matching background.
