### ISSUE TITLE
ctermfg and ctermbg for themer-vim

### ISSUE THREAD

**Issue by spenserblack** [mjswensen/themer#34]
Thanks for this awesome tool!

Looks like themer-vim creates a file that sets colors for `guifg` and `guibg`, but is there any chance `ctermfg` and `ctermbg` could be supported as well?

**Comment by mjswensen** [comment]
Thanks, @spenserblack !

I don't see why not. I haven't been in vim full-time for a couple of years now—would you have any interest in putting together a PR to validate that `ctermfg`/`ctermbg` works for you? Fortunately using the CLI to test the change in your fork should be straightforward:

```sh
$ git clone <your fork of themer repo>
$ cd themer
$ yarn install
# make changes...
$ cd cli/packages
$ ./themer/bin/themer.js -c ./themer-colors-default -t ./themer-vim -o /tmp/output
# then make sure /tmp/output/themer-vim/ThemerVim.vim works
```

If not, I will try to get to it when I get a chance!

**Comment by spenserblack** [comment]
>would you have any interest in putting together a PR to validate that `ctermfg`/`ctermbg` works for you?
Sure, no problem! :smiley:
