### ISSUE TITLE
GNOME Terminal

### ISSUE THREAD

**Issue by agarrharr** [mjswensen/themer#4]
Hey, I just made a color scheme for GNOME terminal for the nova color scheme, and I found themer. It might be cool to add GNOME Terminal support to themer. What do you think?

**Comment by mjswensen** [comment]
Nice! I think that would be awesome. I had actually had GNOME terminal support on my backlog for a while but hadn't gotten around to looking at it yet.

Just looked at your nova GNOME repo—seems like it wouldn't take too much to implement a `themer-gnome-terminal` template using the same ideas. Would you be interested in building/maintaining/publishing the template package yourself (see https://github.com/mjswensen/themer#create-your-own-template)? If not, I would happy to do it in the next few weeks.

**Comment by agarrharr** [comment]
Yeah, I'll work on it myself over at https://github.com/agarrharr/themer-gnome-terminal. I made [an issue over there](https://github.com/agarrharr/themer-gnome-terminal/issues/1) for discussion while it's in progress.

**Comment by mjswensen** [comment]
Great!

**Comment by agarrharr** [comment]
This is done!
