### ISSUE TITLE
Error in generated Vim theme or instructions

### ISSUE THREAD

**Issue by j4nr6n** [mjswensen/themer#43]
<details>
    <summary>The errors</summary>

    Error detected while processing /home/blah/.vimrc:
    line    6:
    E35: No previous regular expression
    Error detected while processing /home/blah/.vim/colors/ThemerVim.vim:
    line   49:
    E121: Undefined variable: s:guishade6
    line   50:
    E121: Undefined variable: s:ctermshade6
    line   58:
    E121: Undefined variable: s:guishade2
    line   59:
    E121: Undefined variable: s:ctermshade2
    line   60:
    E121: Undefined variable: s:guiaccent3
    line   61:
    E121: Undefined variable: s:ctermaccent3
    line   62:
    E121: Undefined variable: s:guiaccent4
    line   63:
    E121: Undefined variable: s:ctermaccent4
    line   64:
    E121: Undefined variable: s:guiaccent2
    line   65:
    E121: Undefined variable: s:ctermaccent2
    line   66:
    E121: Undefined variable: s:guiaccent5
    line   67:
    E121: Undefined variable: s:ctermaccent5
    line   68:
    E121: Undefined variable: s:guiaccent6
    line   69:
    E121: Undefined variable: s:ctermaccent6
    line   70:
    E121: Undefined variable: s:guiaccent7
    line   71:
    E121: Undefined variable: s:ctermaccent7
    line   72:
    E121: Undefined variable: s:guiaccent4
    line   73:
    E121: Undefined variable: s:ctermaccent4
    line   74:
    E121: Undefined variable: s:guiaccent5
    line   75:
    E121: Undefined variable: s:ctermaccent5
    line   76:
    E121: Undefined variable: s:guiaccent0
    line   77:
    E121: Undefined variable: s:ctermaccent0
    line   78:
    E121: Undefined variable: s:guiaccent0
    line   79:
    E121: Undefined variable: s:ctermaccent0
    line   83:
    E121: Undefined variable: s:guiaccent3
    line   84:
    E121: Undefined variable: s:ctermaccent3
    line   85:
    E121: Undefined variable: s:guiaccent2
    line   86:
    E121: Undefined variable: s:ctermaccent2
    line   87:
    E121: Undefined variable: s:guiaccent2
    line   88:
    E121: Undefined variable: s:ctermaccent2
    line   89:
    E121: Undefined variable: s:guiaccent0
    line   90:
    E121: Undefined variable: s:ctermaccent0
    line   94:
    E121: Undefined variable: s:guishade3
    line   95:
    E121: Undefined variable: s:ctermshade3
    line   96:
    E121: Undefined variable: s:guishade3
    line   97:
    E121: Undefined variable: s:ctermshade3
    line   98:
    E121: Undefined variable: s:guishade5
    line   99:
    E121: Undefined variable: s:ctermshade5
    line  100:
    E121: Undefined variable: s:guishade3
    line  101:
    E121: Undefined variable: s:ctermshade3
    line  102:
    E121: Undefined variable: s:guiaccent3
    line  103:
    E121: Undefined variable: s:ctermaccent3
    line  104:
    E121: Undefined variable: s:guiaccent3
    line  105:
    E121: Undefined variable: s:ctermaccent3
    line  106:
    E121: Undefined variable: s:guiaccent2
    line  107:
    E121: Undefined variable: s:ctermaccent2
    line  108:
    E121: Undefined variable: s:guiaccent2
    line  109:
    E121: Undefined variable: s:ctermaccent2
    line  110:
    E121: Undefined variable: s:guiaccent0
    line  111:
    E121: Undefined variable: s:ctermaccent0
    line  119:
    E121: Undefined variable: s:guishade1
    line  120:
    E121: Undefined variable: s:ctermshade1
    line  121:
    E121: Undefined variable: s:guishade2
    line  122:
    E121: Undefined variable: s:ctermshade2
    line  123:
    E121: Undefined variable: s:guishade0
    line  124:
    E121: Undefined variable: s:ctermshade0
    line  125:
    E121: Undefined variable: s:guishade1
    line  126:
    E121: Undefined variable: s:ctermshade1
    line  127:
    E121: Undefined variable: s:guishade1
    line  128:
    E121: Undefined variable: s:ctermshade1
    line  129:
    E121: Undefined variable: s:guiaccent5
    line  130:
    E121: Undefined variable: s:ctermaccent5
    line  131:
    E121: Undefined variable: s:guiaccent3
    line  132:
    E121: Undefined variable: s:ctermaccent3
    line  133:
    E121: Undefined variable: s:guiaccent2
    line  134:
    E121: Undefined variable: s:ctermaccent2
    line  135:
    E121: Undefined variable: s:guiaccent0
    line  136:
    E121: Undefined variable: s:ctermaccent0
    line  137:
    E121: Undefined variable: s:guiaccent2
    line  138:
    E121: Undefined variable: s:ctermaccent2
    line  139:
    E121: Undefined variable: s:guishade7
    line  140:
    E121: Undefined variable: s:ctermshade7
    line  141:
    E121: Undefined variable: s:guishade0
    line  142:
    E121: Undefined variable: s:ctermshade0
    line  143:
    E121: Undefined variable: s:guishade4
    line  144:
    E121: Undefined variable: s:ctermshade4
    line  145:
    E121: Undefined variable: s:guishade4
    line  146:
    E121: Undefined variable: s:ctermshade4
    line  147:
    E121: Undefined variable: s:guishade0
    line  148:
    E121: Undefined variable: s:ctermshade0
    line  149:
    E121: Undefined variable: s:guishade0
    line  150:
    E121: Undefined variable: s:ctermshade0
    line  151:
    E121: Undefined variable: s:guishade2
    line  152:
    E121: Undefined variable: s:ctermshade2
    line  153:
    E121: Undefined variable: s:guishade3
    line  154:
    E121: Undefined variable: s:ctermshade3
    line  155:
    E121: Undefined variable: s:guishade2
    line  156:
    E121: Undefined variable: s:ctermshade2
    line  157:
    E121: Undefined variable: s:guishade0
    line  158:
    E121: Undefined variable: s:ctermshade0
    line  159:
    E121: Undefined variable: s:guishade2
    line  160:
    E121: Undefined variable: s:ctermshade2
    line  161:
    E121: Undefined variable: s:guishade6
    line  162:
    E121: Undefined variable: s:ctermshade6
    line  163:
    E121: Undefined variable: s:guiaccent4
    line  164:
    E121: Undefined variable: s:ctermaccent4
    line  165:
    E121: Undefined variable: s:guiaccent3
    line  166:
    E121: Undefined variable: s:ctermaccent3
    line  167:
    E121: Undefined variable: s:guiaccent0
    line  168:
    E121: Undefined variable: s:ctermaccent0
    line  169:
    E121: Undefined variable: s:guishade7
    line  170:
    E121: Undefined variable: s:ctermshade7
    line  171:
    E121: Undefined variable: s:guishade0
    line  172:
    E121: Undefined variable: s:ctermshade0
    line  173:
    E121: Undefined variable: s:guiaccent7
    line  174:
    E121: Undefined variable: s:ctermaccent7
    line  175:
    E121: Undefined variable: s:guiaccent0
    line  176:
    E121: Undefined variable: s:ctermaccent0
    line  177:
    E121: Undefined variable: s:guiaccent2
    line  178:
    E121: Undefined variable: s:ctermaccent2
    line  179:
    E121: Undefined variable: s:guiaccent4
    line  180:
    E121: Undefined variable: s:ctermaccent4
    line  181:
    E121: Undefined variable: s:guiaccent1
    line  182:
    E121: Undefined variable: s:ctermaccent1
    line  183:
    E121: Undefined variable: s:guishade4
    line  184:
    E121: Undefined variable: s:ctermshade4
    line  185:
    E121: Undefined variable: s:guishade5
    line  186:
    E121: Undefined variable: s:ctermshade5
    line  187:
    E121: Undefined variable: s:guishade1
    line  188:
    E121: Undefined variable: s:ctermshade1
    line  189:
    E121: Undefined variable: s:guishade6
    line  190:
    E121: Undefined variable: s:ctermshade6
    line  191:
    E121: Undefined variable: s:guiaccent5
    line  192:
    E121: Undefined variable: s:ctermaccent5
    line  193:
    E121: Undefined variable: s:guishade1
    line  194:
    E121: Undefined variable: s:ctermshade1
    line  195:
    E121: Undefined variable: s:guiaccent0
    line  196:
    E121: Undefined variable: s:ctermaccent0
    line  197:
    E121: Undefined variable: s:guiaccent0
    line  198:
    E121: Undefined variable: s:ctermaccent0
    line  199:
    E121: Undefined variable: s:guiaccent4
    line  200:
    E121: Undefined variable: s:ctermaccent4
    line  204:
    E121: Undefined variable: s:guiaccent4
    line  205:
    E121: Undefined variable: s:ctermaccent4
    line  206:
    E121: Undefined variable: s:guiaccent5
    line  207:
    E121: Undefined variable: s:ctermaccent5
    line  208:
    E121: Undefined variable: s:guiaccent0
    line  209:
    E121: Undefined variable: s:ctermaccent0
    line  215:
    E108: No such variable: "s:guishade0"
    line  216:
    E108: No such variable: "s:ctermshade0"
</details>

I set background to dark in `.vimrc`, but the generated `readme.md` file makes no mention of this being necessary.
```
set background=dark
```
I'm not sure if this is supposed to be necessary or not. `background` was `light` but I'm not sure what's setting that value, so I just override it right before setting `color ThemerVim`.

**Comment by mjswensen** [comment]
Thank you for logging this! Yes, setting the `background` option is required since a single theme file can  contain both the light and dark variants. I've updated the generated documentation to reflect this.

Now available in `themer-vim@3.2.1` for CLI—will be pushed to web UI shortly.
