### ISSUE TITLE
Terminator terminal

### ISSUE THREAD

**Issue by kinduff** [mjswensen/themer#47]
Big fan of Terminator, if anyone is interested (and it's interesting for the project mantainers), I can do a PR to provide support for this.

**Comment by kinduff** [comment]
@mjswensen Hey! Got a few hours to kill this weekend, would love to revisit this one

**Comment by mjswensen** [comment]
Sounds great, @kinduff ! I recently added a CONTRIBUTING.md file with some docs and shell scripts that hopefully make the process of setting up a new template package quicker/easier. Fee free to reach out with any questions, too.
