### ISSUE TITLE
Swift 4 / High Sierra changes

### ISSUE THREAD

**Issue by citrusui** [mjswensen/themer#5]
Looks like Swift 4 has broken Themer's generation of Terminal.app palettes. Here's a screenshot of what I mean:

<img width="1264" alt="screen shot 2017-08-28 at 9 21 42 am" src="https://user-images.githubusercontent.com/9056756/29775254-76511022-8bd2-11e7-82d8-f7971630719c.png">

NOTE: This only appears to affect Terminal.app. Everything else exports as expected.

**Comment by mjswensen** [comment]
Thanks so much for reporting this, @citrusui . I will start looking into ways to make the Swift script compatible with Swift 4 soon. I've made an issue over at https://github.com/mjswensen/themer-terminal/issues/1 to continue tracking this.
