### ISSUE TITLE
Add Windows terminal support

### ISSUE THREAD

**Issue by DenisBalan** [mjswensen/themer#50]
Windows terminal has also ability to be customized

**Comment by RubenVerg** [comment]
https://www.npmjs.com/package/themer-windows-terminal

**Comment by RubenVerg** [comment]
oh wow is it any similar to mine?
will test for sure

**Comment by mjswensen** [comment]
Was just coming here to post that I had also added yours to the [README](https://github.com/mjswensen/themer#community) as an alternate option, @RubenVerg — thank you for the contribution! 🙏

**Comment by RubenVerg** [comment]
:)

**Comment by RubenVerg** [comment]
also just found a 'slight' bug that in my pack the light one is called dark and vice versa, gotta fix that soon!
