### ISSUE TITLE
Add preview link for Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [mjswensen/themer#54]
The easiest way to distribute/install Firefox themes is with https://color.firefox.com/

It would be really cool if we had a preview link.

Chrome
Firefox ([preview](https://color.firefox.com/?theme=XQAAAAIfAQAAAAAAAABBqYhm849SCia2CaaEGccwS-xNKlhvzmaOMdVyJto3_0aZbNAt3PNrQ1iSTVXcEu1e31YPSoK5zjCy_PUNbE91hBBLFD0EKbAr1p7K4sDUzWXa1VvvKgHJtYrPtlJcXzpqVyO5Zl2xu10F1euGweq54QcxLgLZH1UyemCbEEIjjhR8kGOpVw_BZnXsIVnqOfqC_XWrxonnl9dSi8kLyW9nZOKUH6J6-NQf_6eedQA))
Sketch palettes

the link on desktop shows this (it does not work on mobile)
![Screenshot_20200420-174914_Firefox_Nightly](https://user-images.githubusercontent.com/922368/79765447-4e627b80-832f-11ea-97b8-3d4c198cccd9.png)

**Comment by andreicristianpetcu** [comment]
this is how the theme is converted to the URL in the Color extension and site
https://github.com/mozilla/FirefoxColor/blob/a43d5c66c7dc6f644f4e42e6a53ed1df9e19f099/src/web/index.js#L45-L50

**Comment by mjswensen** [comment]
Resolved by in 31ab98c.
