### ISSUE TITLE
Website freezes when i click on wallpaper preview 

### ISSUE THREAD

**Issue by UraniumR** [mjswensen/themer#57]
For some reason when i click on one of the wallpapers preview the website get frozen and after a whiles a dead bird icon pops out , and i have to refresh it to get it to work again

**Comment by mjswensen** [comment]
Thanks for the heads up, @UraniumR —can you tell me which OS and browser you are using?

**Comment by UraniumR** [comment]
> Thanks for the heads up, @UraniumR —can you tell me which OS and browser you are using?

im using : 
Windows 10 OS Version 1803 (Build 17134.1130)
Browser : Vivaldi ( 2.11.1811.52 (Stable channel) (64-bit) )

**Comment by mjswensen** [comment]
Thanks for that information. Downloading a Windows VM now to see if I can reproduce the issue.

Do you mind sending the full URL where you see the problem?

**Comment by mjswensen** [comment]
@UraniumR still no luck in reproducing the issue on my end—I've added some error tracking through [Sentry](https://sentry.io) in hopes that the issue will surface in the wild and give me a clue as to what's going on.

In the meantime, if you run into it again, let me know. As much detail as possible would be most helpful (URL, series of actions taken before opening up the wallpaper preview, any browser extensions you have installed, etc.).

**Comment by UraniumR** [comment]
Oh, i just went to check out the website , and i have found that the problem have been resolved. 
It told me themer have been updated , so i suppose that the last update fixed the problem.
Thanks <3

**Comment by mjswensen** [comment]
Thanks for the update, @UraniumR !

**Comment by itshaydendev** [comment]
@mjswensen Can we re-open this? I'm running into it on my end.
NixOS 20.03, Chromium browser

**Comment by mjswensen** [comment]
Yep, @itshaydendev . Can you tell me which wallpaper triggers the issue? I have some theories.

**Comment by itshaydendev** [comment]
All except triangles burst and shirts

**Comment by mjswensen** [comment]
Thank you! Do you mind me asking how much RAM you have and how fast your CPU is? My best bet right now is that this is a performance issue with inserting a complex SVG into the DOM.

**Comment by itshaydendev** [comment]
I've got a Ryzen 5 1600 and 16gb of 3200MHz ram underclocked to 3100 for stability reasons with my mobo for now

**Comment by mjswensen** [comment]
Hi folks, I just released an update that converts all wallpaper packages to use PNG format (via canvas) rather than SVG. Since I've never been able to reproduce this issue, I'm hoping that between the format change, using blob URLs rather than `data:` URLs, and better wrapping of the URL in a `useEffect` hook, this problem goes away... but please feel free to reopen if not!
