### ISSUE TITLE
Theme support for Xcode

### ISSUE THREAD

**Issue by eivindml** [mjswensen/themer#6]
Would be cool to also have support for Xcode themes. Themes are in a XML format. See examples [here](https://github.com/hdoria/xcode-themes).

**Comment by mjswensen** [comment]
Definitely have had Xcode on my radar for a while—thank you for logging this, and for providing a link to useful resources. 👍

**Comment by mjswensen** [comment]
@eivindml : I've added support for Xcode (see [themer-xcode](https://github.com/mjswensen/themer-xcode) or [themer-gui](https://github.com/mjswensen/themer-gui)). I don't use Xcode full-time so if anything seems funky about the outputted themes feel free to log an issue over on [themer-xcode/issues](https://github.com/mjswensen/themer-xcode/issues).

**Comment by eivindml** [comment]
awesome stuff. Looks great for now. Will report if any thing funky appears 👍
