### ISSUE TITLE
feature request: export to CSS?

### ISSUE THREAD

**Issue by Offirmo** [mjswensen/themer#67]

**Comment by mjswensen** [comment]
I like this idea, @Offirmo . Here is what I'm thinking to do:

If the color set only exposes **either** a dark variant or a light variant, output a file like this:

```css
:root {
  --shade0: <color>;
  --shade1: <color>;
  /* etc. */

  --accent0: <color>;
  --accent1: <color>;
  /* etc. */
}
```

If the color set exposes **both** a dark variant and a light variant, output a file like this:

```css
:root {
  --shade0: <color>;
  --shade1: <color>;
  /* etc. */

  --accent0: <color>;
  --accent1: <color>;
  /* etc. */
}
```

**Comment by mjswensen** [comment]
(TIL: if you press `command`-`shift`-`return` while typing a comment, the issue gets closed. Whoops 🙄 )

**Comment by mjswensen** [comment]
@Offirmo this is deployed now to themer.dev and available for CLI at `@themer/css`. I went with a slightly different format than the one proposed above—feel free to try it out and let me know if some other structure would be useful.
