### ISSUE TITLE
Adding support to export colors/themes for Android

### ISSUE THREAD

**Issue by PDDStudio** [mjswensen/themer#8]
It would be cool to be able to export Colors/Themes/Styles for Android-Apps.
Colors are defined in xml.

Sample:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<!-- colors for AppTheme.Blue -->
	<color name="colorPrimary">#3F51B5</color>
	<color name="colorPrimaryDark">#303F9F</color>
	<color name="colorAccent">#FF4081</color>
	<!-- colors for AppTheme.Red -->
	<color name="colorPrimaryRed">#F44336</color>
	<color name="colorPrimaryDarkRed">#D32F2F</color>
	<color name="colorAccentRed">#607D8B</color>
	<!-- colors for AppTheme.Green -->
	<color name="colorPrimaryGreen">#4CAF50</color>
	<color name="colorPrimaryDarkGreen">#388E3C</color>
	<color name="colorAccentGreen">#795548</color>
	<!-- colors for AppTheme.DarkOrange -->
	<color name="colorPrimaryDarkOrange">#FF9800</color>
	<color name="colorPrimaryDarkDarkOrange">#F57C00</color>
	<color name="colorAccentDarkOrange">#9E9E9E</color>
	<color name="black_overlay">#66000000</color>
</resources>
```

**Comment by mjswensen** [comment]
Nice idea, thanks for submitting, @PDDStudio . I haven't done Android dev since school—would you have any interest in implementing this as a template package? ([themer-alfred](https://github.com/mjswensen/themer-alfred) is an example of how a template package is done.)

**Comment by PDDStudio** [comment]
Hi @mjswensen sorry for my late reply! I could give it a try, though I'm not that good in JS.

**Comment by PDDStudio** [comment]
@mjswensen Take a look at [this](https://github.com/PDDStudio/themer-android)

**Comment by mjswensen** [comment]
@PDDStudio 👏 Nice! I will add a link to your repo on the readme so others can find it!
