### ISSUE TITLE
report powerline-rs support

### ISSUE THREAD

**Issue by lafleurdeboum** [mjswensen/themer#87]
## `powerline-rs` template
I implemented support for the [`powerline-rs`](https://gitlab.com/jD91mZM2/powerline-rs) program, basically a re-implementation of `powerline` written in rust. I thought this soft is not vital, so I'd keep it as a third-party plugin. On the other hand, you have `vim-lightline` in the main project, and `powerline-rs` is basically the same thing for `zsh`/`bash`.

It's available in npm with
``` sh
npm install themer-powerline-rs
```
the source code is GPLv2, available [here](https://gitlab.com/lafleurdeboum/themer-powerline-rs) in gitlab. Would you consider adding the link to the community-contributed templates ? That would be fine enough for me.

Thank you for this great soft !

**Comment by mjswensen** [comment]
Hi @lafleurdeboum , thank you so much for bringing this to my attention. Yes, I would love to feature `themer-powerline-rs` in the community section of the README. Will do so shortly.

**Comment by lafleurdeboum** [comment]
That's nice, thank you. Just wanted to say that I updated it to use the 8 more basic colors set by themer. As a matter of fact, `powerline-rs` only supports 256 color codes. But if it uses the basic color codes, the terminal emulator in turn is able to display the true needed colors, and (as far as I can tell) we get a real match.
